// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
import * as db_city from "../db_city"

// definition: API.System.City@CityList
export interface CityList {
  from: number;
  list: db_city.Full[];
}


// tag-rt-api-builder-end