// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package api_system_city

import (
"github.com/ootiny/libs/rt/_rt_system_"
)

type CityTest struct {
	Name string`json:"name" required:"true"`
	Location DB.Geo@Full`json:"location" required:"true"`
	Description string`json:"description"`
}

type FuncGetCity = func(id string) (, Error)
type HookGetCity = func(fn FuncGetCity) error

func init() {
	__system.RegisterHandler("API.System.City", func(w __system.IResponse, r __system.IRequest) {

	})
}
//tag-rt-api-builder-end