// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_geo
import (
	"github.com/ootiny/rt/server/runtime"
)

// definition: DB.Geo@Full
type Full struct {
	Id string `json:"id" required:"false"`
	Latitude float64 `json:"latitude" required:"false"`
	Longitude float64 `json:"longitude" required:"false"`
}

type FullBytes = []byte
func UnmarshalFull(data []byte, v *Full) error {
	 return runtime.JsonUnmarshal(data, v)
}
func FullBytesToFull(data []byte) (*Full, error) {
	var v Full
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}


// tag-rt-api-builder-end