// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_geo


// definition: DB.Geo@Full
type Full struct {
	Id string `json:"id" required:"false"`
	Latitude float64 `json:"latitude" required:"false"`
	Longitude float64 `json:"longitude" required:"false"`
}



//tag-rt-api-builder-end