// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_geo


type Full struct {
	Id string `json:"id"`
	Latitude float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}



//tag-rt-api-builder-end