// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_city
import (
	"github.com/ootiny/rt/server/runtime/db_geo"
	"github.com/ootiny/rt/server/runtime"
)

// definition: DB.City@Full
type Full struct {
	Id string `json:"id" required:"true"`
	Name string `json:"name" required:"true"`
	Geo db_geo.Full `json:"geo" required:"false"`
	Active bool `json:"active" required:"false"`
}

type FullBytes = []byte
func UnmarshalFull(data []byte, v *Full) error {
	 return runtime.JsonUnmarshal(data, v)
}
func FullBytesToFull(data []byte) (*Full, error) {
	var v Full
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

// definition: DB.City@Simple
type Simple struct {
	Id string `json:"id" required:"true"`
	Name string `json:"name" required:"true"`
}

type SimpleBytes = []byte
func UnmarshalSimple(data []byte, v *Simple) error {
	 return runtime.JsonUnmarshal(data, v)
}
func SimpleBytesToSimple(data []byte) (*Simple, error) {
	var v Simple
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}


// tag-rt-api-builder-end