// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package api_system_city
import (
	"github.com/ootiny/rt/server/runtime/db_city"
	"github.com/ootiny/rt/server/runtime"
)

// definition: API.System.City@CityList
type CityList struct {
	From int64 `json:"from" required:"true"`
	List []db_city.Full `json:"list" required:"true"`
}

// Action: API.System.City:Test
var fnTest FuncTest
type FuncTest = func() ([]db_city.Simple, runtime.Error)
func HookTest (fn FuncTest) {
	fnTest = fn
}

// Action: API.System.City:GetCityList
var fnGetCityList FuncGetCityList
type FuncGetCityList = func(country string) (CityList, runtime.Error)
func HookGetCityList (fn FuncGetCityList) {
	fnGetCityList = fn
}

func init() {
	runtime.RegisterHandler("API.System.City:Test", func(ctx runtime.Context, response runtime.Response, data []byte) *runtime.Return {
		if fnTest == nil {
			return &runtime.Return{Code: runtime.ErrActionNotImplemented, Message: "API.System.City:Test is not implemented"}
		} else if result, err := fnTest(); err != nil {
			return &runtime.Return{Code: err.GetCode(), Message: err.Error()}
		} else {
			return &runtime.Return{Data: result}
		}
	})
	runtime.RegisterHandler("API.System.City:GetCityList", func(ctx runtime.Context, response runtime.Response, data []byte) *runtime.Return {
		var v struct {
			Country string `json:"country" required:"true"`
		}
		if err := runtime.JsonUnmarshal(data, &v); err != nil {
			return nil
		}

		if fnGetCityList == nil {
			return &runtime.Return{Code: runtime.ErrActionNotImplemented, Message: "API.System.City:GetCityList is not implemented"}
		} else if result, err := fnGetCityList(v.Country); err != nil {
			return &runtime.Return{Code: err.GetCode(), Message: err.Error()}
		} else {
			return &runtime.Return{Data: result}
		}
	})
}
// tag-rt-api-builder-end