// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package api_system_city

import (
	"github.com/ootiny/rt/libs/rt/main/db_city"
)

type CityList struct {
	From int64 `json:"from" required:"true"`
	List []db_city.Full `json:"list" required:"true"`
}



//tag-rt-api-builder-end