// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
import * as db_geo from "../db_geo"

// definition: DB.City@Full
export interface Full {
  id: string;
  name: string;
  geo: db_geo.Full;
  active: boolean;
}


// tag-rt-api-builder-end