// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_city

import (
	"github.com/ootiny/rt/runtime/db_geo"
)

// definition: DB.City@Full
type Full struct {
	Id string `json:"id" required:"true"`
	Name string `json:"name" required:"true"`
	Geo db_geo.Full `json:"geo" required:"false"`
	Active bool `json:"active" required:"false"`
}



//tag-rt-api-builder-end