// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_city

import (
	"github.com/ootiny/rt/libs/rt/main/db_geo"
)

type Full struct {
	Id string `json:"id" required:"true"`
	Name string `json:"name" required:"true"`
	Geo db_geo.Full `json:"geo"`
	Active bool `json:"active"`
}



//tag-rt-api-builder-end